version: "3"

services:
  keycloak-db:
    container_name: keycloak_db_container
    image: postgres:15.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "127.0.0.1:5437:5437"
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - keycloak-db
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: "/tmp/export.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - "./keycloak/export.json:/tmp/export.json"
    image: jboss/keycloak:16.1.1
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

  app:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: volginta/user-service
    container_name: user-service
    privileged: true
    depends_on:
      - keycloak
    environment:
      KC_URL: http://keycloak:8080/auth
      KC_REALM: shop
      KC_CLIENT_ID: shop-app
      KC_SECRET: hiOfyA97ur2AatrfK55XJ5a3WyubdB5t
    ports:
      - "8081:8081"
    networks:
      - local-keycloak

networks:
  local-keycloak:
