version: "3"

services:
  keycloak-db:
    container_name: keycloak_db_container
    image: postgres:15.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    depends_on:
      - keycloak-db
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: "/tmp/export.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - "./keycloak/export.json:/tmp/export.json"
    image: jboss/keycloak:16.1.1
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: volginta/user-service
    container_name: user-service
    privileged: true
    depends_on:
      - keycloak
    environment:
      KC_URL: http://keycloak:8080/auth
      KC_REALM: shop
      KC_CLIENT_ID: shop-app
      KC_SECRET: hiOfyA97ur2AatrfK55XJ5a3WyubdB5t
      EUREKA_SERVICE_SERVER_PORT: 8084
      EUREKA_SERVICE_SERVER_HOSTNAME: eureka-service
      eureka.instance.preferIpAddress: true
      eureka.instance.ip-address: 127.0.0.1
    ports:
      - "8081:8081"

  book-store-service-db:
    image: postgres:15.5
    restart: unless-stopped
    container_name: book-store-service-db
    environment:
      POSTGRES_DB: book_store
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store_pass

  book-store-service:
    build:
      context: ./book-store-service
      dockerfile: Dockerfile
    image: volginta/book-store-service
    container_name: book-store-service
    privileged: true
    depends_on:
      - keycloak
      - book-store-service-db
    environment:
      BOOK_STORE_PROJECT_PROFILE: prod
      BOOK_STORE_DB_URL: jdbc:postgresql://book-store-service-db:5432/book_store
      BOOK_STORE_DB_USERNAME: store
      BOOK_STORE_DB_PASSWORD: store_pass
      BOOK_STORE_KEYCLOAK_CERT: http://localhost:8080/auth/realms/shop/protocol/openid-connect/certs
      EUREKA_SERVICE_SERVER_PORT: 8084
      EUREKA_SERVICE_SERVER_HOSTNAME: eureka-service
      eureka.instance.preferIpAddress: true
      eureka.instance.ip-address: 127.0.0.1
    ports:
      - "8082:8082"

  eureka-service:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    image: belovdp/eureka-service
    container_name: eureka-service
    privileged: true
    environment:
      EUREKA_SERVICE_SERVER_HOSTNAME: localhost
    ports:
      - "8084:8084"
