--liquibase formatted sql

--changeset VolginTA:createTables
CREATE TABLE genres  (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_genres PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE authors (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_authors PRIMARY KEY,
    fio      VARCHAR(255) NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE books (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_books PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    published DATE NOT NULL,
    number_of BIGINT,
    genre_id  BIGINT,
    author_id BIGINT,
    FOREIGN KEY (genre_id)  REFERENCES genres (id),
    FOREIGN KEY (author_id) REFERENCES authors (id)
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_products PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    price       DECIMAL DEFAULT '0.0' NOT NULL,
    disabled    BOOLEAN
);

CREATE TABLE products_books (
    product_id BIGINT not null,
    book_id    BIGINT not null,
    PRIMARY KEY (product_id, book_id),
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    FOREIGN KEY (book_id)    REFERENCES books    (id) ON DELETE CASCADE
);
