server:
  port: 8081

spring:
  data:
    rest:
      basePath: /

keycloak:
  realm: ${kc.realm:shop}
  auth-server-url: ${kc.url:http://localhost:8080/auth}
  resource: ${kc.client_id:shop-app}
  credentials:
    secret: ${kc.secret:hiOfyA97ur2AatrfK55XJ5a3WyubdB5t}
  use-resource-role-mappings: true
  bearer-only: true

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
